### PR TITLE
feat(): create isolate buttons example

### PR DESCRIPTION
**Pull request by Cmdv**

### CODE REVIEW

**Comment by Cmdv** [comment]
isolated

@staltz just need some pointers as to how I should handle the isolation. 

Functionally it does what apart from `delete` button, it's just not isolated though.

I tried moving model + intent from `index.js` into into the `isolate-button.js`. I don't know how to get the `sinks` back from the `isolate-button` because right now I map over my props in my index view to determine how many buttons to show!!

Do you think this is the right direction and how can I actually plug in the isolation? :)

**Comment by Cmdv** [comment]
not to worry going to take another stab at it with a different method, the way I dictate how many buttons should be shown is too adhock!!

**Comment by Cmdv** [comment]
@staltz I'm going to close the PR, I was unable to work out how to pipe isolated components for this user case. Had all the needed elements but couldn't work out my index/parent model and how to add/remove objects of the state array in the isolated component. But probably needed to also be done in the index model!

**Comment by staltz** [comment]
Thanks @Cmdv anyway for what you did so far and sorry if I wasn't able to review it timely

**Comment by Cmdv** [comment]
It's all good, looks like Tylor used part of it to build his version :)

**Pull request closed without merging**
