### PR TITLE
[WIP] Fix up hot reloading example

### PR DESCRIPTION
**Pull request by Widdershin**
**Please don't merge!**

Still need to land https://github.com/Widdershin/cycle-restart/pull/21

This works but for the above PR, because request is not set on HTTP response$

### CODE REVIEW

**Comment by Widdershin** [comment]
Okay, so it's mostly working now @staltz. Sometimes after restarting searching doesn't work, could you have a look and see how it goes for you?

**Comment by staltz** [comment]
I'll check this. Thanks @Widdershin !

**Comment by staltz** [comment]
I think I'm still really stuck with it. I started the server and went to localhost:8000 but it doesn't hot reload anything. E.g. `module.hot` is undefined.

**Comment by Widdershin** [comment]
Does it work if you `npm run live` and open `index.html`?

**Comment by staltz** [comment]
That works! Thanks.

I was able to experiment with some basic replacements, but indeed I found the same/similar searching bug that you found. Here's the root of the problem:

`res$$` is what the JSONP (or HTTP) driver gives as source, and it's important to use the `request` reference from `res$.request`. But I noticed `.request` was undefined. I checked with the debugger, and `res$` was a TapObservable (from `.do()`), and that's because in restartable we have:

``` js
function recordObservableSource(_ref3, source) {
    // ...
    if (typeof event.subscribe === 'function') {
      var loggedEvent$ = event.do(function (response) {
        log.push({ event: _rx.Observable.just(response), time: new Date(), stream: source$, identifier: ':root' });
      });

      source$.onNext(loggedEvent$);
    }
```

A hacky fix to this would be to check if `event.request` exists, and then attach that same also to `loggedEvent$.request` but this may be brittle in the general case. Is it very important to `log.push()` the inner Observable?

**Comment by Widdershin** [comment]
If you npm install, that issue should be fixed in the latest version of
cycle-restart.

**Comment by staltz** [comment]
Nice :+1:

**Comment by staltz** [comment]
@Widdershin I had a bug, it looked like this:

This code

``` diff
 const drivers = {
+  DOM: restartable(makeDOMDriver('#main-container'), {pauseSinksWhileReplaying: false}),
   JSONP: restartable(makeJSONPDriver()),
   preventDefault: restartable(preventDefaultSinkDriver),
 }
```

Leads to this
bad

("Moon" should not appear. The dropdown menu should)

---

And this code

``` diff
 const drivers = {
+  DOM: makeDOMDriver('#main-container'),
   JSONP: restartable(makeJSONPDriver()),
   preventDefault: restartable(preventDefaultSinkDriver),
 }
```

leads to this (correct) behavior:

good

---

Both of these cases above were run without hot reloading actually.

**Comment by staltz** [comment]
I pushed some small changes/fixes, just to help if you need the latest code.

**Pull request merged**
